import { WavyBackground } from 'modecraft/components/events/wavy-background';
import styles from './page.module.css';
import EventGrid from 'modecraft/components/events/EventGrid';
import { Suspense } from 'react';
import { getEvents } from 'modecraft/lib/events';

export const metadata = {
    title: 'ModeCraft | Events',
    description: 'Generated by create next app',
};

async function Events() {
    const events = await getEvents();
    return <EventGrid events={events} />;
}

export default function EventsPage() {
    return (
        <div className={styles.pageContainer}>
            <WavyBackground className={styles.wavyBackground}>
                <div className={styles.heroContent}>
                    <p className={styles.heroTitle}>
                        ファッションの未来を共に探求し、創造的な出会いを楽しもう
                    </p>
                    <p className={styles.heroSubtitle}>
                        モードクラフト | イベント
                    </p>
                </div>
                <main className={styles.mainContent}>
                    <Suspense fallback={<div className={styles.loading}>Fetching Products....</div>}>
                        <Events />
                    </Suspense>
                </main>
            </WavyBackground>

        </div>
    );
}